# Generated by Django 5.2.16 on 2026-07-31 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_archived_at_client_archived_by_and_more'),
        ('sales', '0004_backfill_closed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_hash', models.CharField(blank=True, max_length=64)),
                ('accent_color', models.CharField(blank=True, max_length=16)),
                ('secondary_color', models.CharField(blank=True, max_length=16)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('service_category', models.CharField(blank=True, max_length=120)),
                ('document_prefix', models.CharField(help_text='Visible number prefix, e.g. FUEL or MORPH-STUDIO.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_brand_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('quotation', 'Quotation'), ('payment_acknowledgment', 'Payment acknowledgment')], max_length=32)),
                ('document_number', models.CharField(max_length=64, unique=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('void', 'Void')], default='issued', max_length=12)),
                ('template_version', models.CharField(default='v1', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='branding.brandprofile')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='clients.client')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sales.deal')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocumentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_brand_key', models.CharField(max_length=40)),
                ('presentation_brand_name', models.CharField(max_length=255)),
                ('legal_entity_key', models.CharField(max_length=40)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('tax_number', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('bank_details', models.TextField(blank=True)),
                ('accent_color', models.CharField(blank=True, max_length=16)),
                ('document_prefix', models.CharField(blank=True, max_length=40)),
                ('logo_hash', models.CharField(blank=True, max_length=64)),
                ('logo_reference', models.CharField(blank=True, max_length=255)),
                ('signatory_name', models.CharField(blank=True, max_length=255)),
                ('signatory_title', models.CharField(blank=True, max_length=255)),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('signature_reference', models.CharField(blank=True, max_length=255)),
                ('terms', models.TextField(blank=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('template_version', models.CharField(blank=True, max_length=20)),
                ('generated_by_username', models.CharField(blank=True, max_length=150)),
                ('generated_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='branding.generateddocument')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=120)),
                ('tax_number', models.CharField(blank=True, max_length=120)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('bank_details', models.TextField(blank=True)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_title', models.CharField(blank=True, max_length=255)),
                ('legal_terms', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_legal_entities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Legal entities',
                'ordering': ['legal_name'],
            },
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='branding.legalentity'),
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice'), ('contract', 'Contract'), ('receipt', 'Receipt'), ('quotation', 'Quotation'), ('payment_acknowledgment', 'Payment acknowledgment')], max_length=32)),
                ('year', models.PositiveIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequences', to='branding.legalentity')),
            ],
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='legal_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brands', to='branding.legalentity'),
        ),
        migrations.CreateModel(
            name='Signatory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('signature_image', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('signature_hash', models.CharField(blank=True, max_length=64)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatories', to='branding.legalentity')),
            ],
            options={
                'verbose_name_plural': 'Signatories',
                'ordering': ['legal_entity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='brandprofile',
            name='default_signatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_brands', to='branding.signatory'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['document_type', '-created_at'], name='branding_ge_documen_1aaec6_idx'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['brand', '-created_at'], name='branding_ge_brand_i_bf38b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('legal_entity', 'document_type', 'year'), name='unique_sequence_scope'),
        ),
    ]
