# Generated by Django 5.2.16 on 2026-07-30 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salessettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
