# Generated by Django 5.2.14 on 2026-06-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommandlog',
            name='tier',
            field=models.CharField(choices=[('auto', 'Auto'), ('confirm', 'Confirm'), ('blocked', 'Blocked'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='aicommandlog',
            name='outcome',
            field=models.CharField(choices=[('executed', 'Executed'), ('confirmation_required', 'Confirmation required'), ('confirmed', 'Confirmed'), ('blocked', 'Blocked'), ('action_taken', 'Action taken'), ('draft_returned', 'Draft returned'), ('error', 'Error')], max_length=30),
        ),
    ]
