# Generated by Django 5.2.14 on 2026-06-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_commands', '0002_aicommandlog_tier_alter_aicommandlog_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicommandlog',
            name='action_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aicommandlog',
            name='undone_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aicommandlog',
            name='outcome',
            field=models.CharField(choices=[('executed', 'Executed'), ('confirmation_required', 'Confirmation required'), ('confirmed', 'Confirmed'), ('blocked', 'Blocked'), ('undone', 'Undone'), ('action_taken', 'Action taken'), ('draft_returned', 'Draft returned'), ('error', 'Error')], max_length=30),
        ),
    ]
