# Generated by Django 5.2.16 on 2026-07-31 00:12

import datetime
import django.db.models.deletion
import workforce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_tracking_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='Asia/Amman', max_length=64)),
                ('employment_start_date', models.DateField(blank=True, null=True)),
                ('employment_end_date', models.DateField(blank=True, null=True)),
                ('working_days', models.JSONField(default=workforce.models.default_working_days)),
                ('earliest_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('latest_end_time', models.TimeField(default=datetime.time(21, 0))),
                ('daily_target_minutes', models.PositiveIntegerField(default=180)),
                ('monthly_target_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_currency', models.CharField(default='JOD', max_length=3)),
                ('overtime_allowed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_work_policies', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_policy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee work policy',
                'verbose_name_plural': 'Employee work policies',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='WorkPolicyException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exception_type', models.CharField(choices=[('extra_working_day', 'Extra working day'), ('custom_window', 'Custom start/end time'), ('holiday', 'Holiday (day off)'), ('one_day_override', 'One-day override')], max_length=32)),
                ('custom_start_time', models.TimeField(blank=True, null=True)),
                ('custom_end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_exceptions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='workforce.employeeworkpolicy')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('policy', 'date'), name='one_exception_per_policy_date')],
            },
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Amman', max_length=64)),
                ('daily_target_minutes', models.PositiveIntegerField(default=180)),
                ('window_start_time', models.TimeField(default=datetime.time(9, 0))),
                ('window_end_time', models.TimeField(default=datetime.time(21, 0))),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField()),
                ('work_date', models.DateField()),
                ('closing_reason', models.CharField(blank=True, choices=[('manual_end', 'Manually ended'), ('inactivity', 'Closed by inactivity'), ('working_window_ended', 'Working window ended (9:00 PM)'), ('admin_closed', 'Closed by administrator'), ('policy_disabled', 'Policy disabled'), ('system_reconciliation', 'System reconciliation')], max_length=32)),
                ('credited_seconds', models.PositiveIntegerField(default=0)),
                ('auto_closed', models.BooleanField(default=False)),
                ('start_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('start_user_agent', models.CharField(blank=True, max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='workforce.employeeworkpolicy')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['employee', '-started_at'], name='workforce_w_employe_ea0265_idx'), models.Index(fields=['employee', 'work_date'], name='workforce_w_employe_49bf60_idx'), models.Index(fields=['ended_at'], name='workforce_w_ended_a_840f59_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ended_at__isnull', True)), fields=('employee',), name='one_active_session_per_employee')],
            },
        ),
    ]
