# Generated by Django 5.2.16 on 2026-07-31 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_client_archived_at_client_archived_by_and_more'),
        ('sales', '0004_backfill_closed_at'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, help_text='Campaign or source label.', max_length=120)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('previewed', 'Previewed'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('invalid_count', models.PositiveIntegerField(default=0)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('assigned_count', models.PositiveIntegerField(default=0)),
                ('validation_result', models.JSONField(blank=True, default=dict)),
                ('stored_file', models.FileField(blank=True, null=True, upload_to='lead_imports/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_lead_batches', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('original_phone', models.CharField(max_length=64)),
                ('normalized_phone', models.CharField(blank=True, db_index=True, max_length=32)),
                ('country_context', models.CharField(blank=True, max_length=8)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('no_answer', 'No answer'), ('follow_up', 'Follow up'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('converted', 'Converted')], default='new', max_length=20)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_leads', to=settings.AUTH_USER_MODEL)),
                ('converted_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='clients.client')),
                ('converted_deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_leads', to='sales.deal')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_leads', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='leads.leadimportbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadContactAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email'), ('other', 'Other')], default='call', max_length=20)),
                ('outcome', models.CharField(choices=[('reached', 'Reached'), ('no_answer', 'No answer'), ('busy', 'Busy'), ('wrong_number', 'Wrong number'), ('callback_requested', 'Callback requested'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('other', 'Other')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('resulting_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('no_answer', 'No answer'), ('follow_up', 'Follow up'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('converted', 'Converted')], max_length=20)),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contact_attempts', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attempts', to='leads.lead')),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contact_attempts', to='workforce.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['lead', '-created_at'], name='leads_leadc_lead_id_a815e0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['assigned_to', 'status'], name='leads_lead_assigne_92225c_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='leads_lead_status_e23abe_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['normalized_phone'], name='leads_lead_normali_b242fd_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['follow_up_at'], name='leads_lead_follow__258934_idx'),
        ),
    ]
