# Generated by Django 5.2.16 on 2026-07-31 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('shift', 'Shift'), ('policy', 'Policy'), ('crm', 'CRM record'), ('lead', 'Lead'), ('document', 'Document'), ('user', 'User administration'), ('branding', 'Branding'), ('ai', 'AI command'), ('security', 'Security'), ('telemetry', 'UI telemetry')], max_length=20)),
                ('source', models.CharField(choices=[('server', 'Server'), ('client', 'Client')], default='server', max_length=10)),
                ('entity_type', models.CharField(blank=True, max_length=64)),
                ('entity_id', models.CharField(blank=True, max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('old_values', models.JSONField(blank=True, default=dict)),
                ('new_values', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=400)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('work_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='workforce.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='audit_audit_created_e208ff_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_605853_idx'), models.Index(fields=['category', '-created_at'], name='audit_audit_categor_27173c_idx'), models.Index(fields=['action'], name='audit_audit_action_203f66_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__0bff9a_idx'), models.Index(fields=['work_session'], name='audit_audit_work_se_14fc2e_idx')],
            },
        ),
    ]
